prototype/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from feedback_manager import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^(?P<code>\w{16})/$', views.FeedBackView.as_view(), name='show_questions'),
    url(r'view/(?P<feedback_id>\d+)/$', views.ViewFeedback.as_view(), name='view_feedback'),
    url(r'thanks/$', views.FeedbackSubmittedView.as_view(), name='view_thanks'),
    url(r'home/$', views.Home.as_view(), name='home'),
    url(r'avail_time/$', views.avail_time, name='avail_time'),
]

#urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT})
urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = 'Feedback Administration'

feedback_manager/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.contrib.auth.models import User

type_status = (('A', 'Active'), ('I', 'Inactive'))

feedback_status = (
	('I', 'In Progress'),
	('C', 'Complete'),
	('A', 'Assigned'))

question_types = (
	('S','Subjective'),
	('O','Objective'),
	('C','Checkbox'),
	('G','Grades'),
	('A','Appointment'))

appointment_status = (
	('A','Available'),
	('U','Unavailable'))

grade_types = (
	('A','A'),
	('B','B'),
	('C','C'))

days_list = (
	('1','Monday'),
	('2','Tuesday'))

feedback_types = (
	('prior results','Results'),
	('appointment','Appointment'),
	('review','Take a Review'),
	('future courses','Available courses'))

class Question(models.Model):
	text = models.TextField()
	status = models.CharField(max_length=10, choices=type_status, default='A')
	question_type = models.CharField(max_length=1, choices=question_types, default='S')

	def __str__(self):
		return self.text

	def is_subjective(self):
		if self.question_type == 'S':
			return True
		return False

	def is_objective(self):
		if self.question_type == 'O':
			return True
		return False

	def is_checkbox(self):
		if self.question_type == 'C':
			return True
		return False

	def is_appointment(self):
		if self.question_type == 'A':
			return True
		return False

class Day(models.Model):
	name = models.TextField()

	def __str__(self):
		return self.name

class Appointment(models.Model):
	#day = models.ForeignKey(Day)
	date = models.DateField(null=True)
	day = models.CharField(max_length=1, choices=days_list)
	start_time = models.TimeField()
	finish = models.TimeField()
	available = models.CharField(max_length=1, choices=appointment_status, default='A')

	def make_appointment(self):
		self.available = 'U'
		self.save()

	def __str__(self):
		return str(self.day)+'-'+str(self.start_time)

class Subject(models.Model):
	subject_name = models.CharField(max_length=48)

	def __str__(self):
		return self.subject_name

class Grade(models.Model):
	grade_obtained = models.CharField(max_length=1)

	def __str__(self):
		return self.grade_obtained

class FeedbackType(models.Model):
	#name = models.CharField(max_length=48, unique=True)
	name = models.CharField(max_length=48, unique=True, choices=feedback_types)
	questions = models.ManyToManyField(Question, blank=True)
	status = models.CharField(max_length=10, choices=type_status, default='A')
	order_id = models.IntegerField(default=0)

	def is_results(self):
		if self.name == 'prior results':
			return True
		return False

	def is_appointment(self):
		if self.name == 'appointment':
			return True
		return False


	def __str__(self):
		return self.name

class TimeTable(models.Model):
	start_date = models.DateField(null=True)
	end_date = models.DateField(null=True)
	# start_time = models.TimeField(null=True)
	# end_time = models.TimeField(null=True)

class TimeSlot(models.Model):
	appointment_time = models.TextField()
	time_table = models.ForeignKey(TimeTable)

	def __str__(self):
		return self.appointment_time

class NewAppointment(models.Model):
	date = models.DateField(null=True)
	time_slot = models.ForeignKey(TimeSlot)
	available = models.CharField(max_length=1, choices=appointment_status, default='A')

	def make_appointment(self):
		self.available = 'U'
		self.save()

	def __str__(self):
		return str(self.date)+'-'+str(self.time_slot)

class Feedback(models.Model):
	name = models.CharField(max_length=48)
	feedback_type = models.ForeignKey(FeedbackType, null=True)
	user = models.ForeignKey(User, related_name='assigned_feedbacks')
	created_by = models.ForeignKey(User, related_name='feedbacks')
	code = models.CharField(max_length=16, unique=True, blank=True)
	started_on = models.DateTimeField(null=True)
	ended_on = models.DateTimeField(null=True)
	status = models.CharField(max_length=10, choices=feedback_status, default='A')
	questions = models.ManyToManyField(Question, through='FeedbackQusetionMap')
	appointment = models.ForeignKey(Appointment, null=True,blank=True)

	def start_feedback(self):
		self.status = 'I'
		self.started_on = datetime.datetime.now()
		self.save()

	def end_feedback(self):
		self.status = 'C'
		self.ended_on = datetime.datetime.now()
		self.save()

	def is_completed(self):
		return self.status == 'C'
		self.save()

	def __str__(self):
		return "%s (%s)" %(self.user.get_full_name(), self.feedback_type.name)

class FeedbackAppointmentMap(models.Model):
	feedback = models.ForeignKey(Feedback, null=False)
	appointment = models.ForeignKey(NewAppointment, null=True)
	submitted_at = models.DateTimeField(null=True, blank=True)

	def __str__(self):
		return str(self.feedback)+str(self.appointment)

class FeedbackQusetionMap(models.Model):
	feedback = models.ForeignKey(Feedback, null=False, related_name='map_feedbacks')
	question = models.ForeignKey(Question, null=False)
	submitted_answer = models.TextField(null=True, blank=True)
	submitted_at = models.DateTimeField(null=True, blank=True)
	
	def __str__(self):
		return str(self.feedback)

	def get_submitted_answer(self):
		"""
		"""	
		if self.question.is_subjective():
			return self.submitted_answer
		else:
			return ",".join(self.fqom.all().values_list('submitted_option__text',
				flat=True))

class Option(models.Model):
	text = models.CharField(max_length=48)
	question = models.ForeignKey(Question, null=False, related_name='options')

	def __str__(self):
		return self.text

class FeedbackQusetionOptionMap(models.Model):
	feedback_qusetion_map = models.ForeignKey(FeedbackQusetionMap, null=False, related_name="fqom")
	submitted_option = models.ForeignKey(Option, null=False, blank=True,
		related_name='submited_option')

	def __str__(self):
		return str(self.feedback_qusetion_map)

class UserGradeMap(models.Model):
	user = models.ForeignKey(User)
	subject = models.ForeignKey(Subject, null=True, blank=True)
	grade = models.CharField(max_length=1, choices=grade_types, default='A')
	#feedback = models.ForeignKey(Feedback, null=True, blank=True, related_name='map_grade_feedback')

	def __str__(self):
		return (str(self.user) + '-' + str(self.subject))

feedback_manager/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.core import serializers

from models import *
from datetime import datetime
import pdb

class FeedBackView(View):
	"""
	"""

	def get(self, request, code):
		"""
		"""
		obj = Feedback.objects.get(code=code)
		user = obj.user
		grade_obj = UserGradeMap.objects.filter(user=user)
		if not obj.is_completed():
			obj.start_feedback()
			if obj.feedback_type.is_results():
				obj.end_feedback()
			return render(request, 'feedback_form.html', {'objs':obj, 'grade_objs':grade_obj})
		else:
			return render(request, 'thanks.html', {'msg': 'Oops! You have already submitted this feedback'})

	def post(self, request, code):
		"""
		"""
		print "request  >> ", request.POST
		feedback_obj = Feedback.objects.get(code=code)
		feedback_qusetion_map_ids = request.POST.getlist('feedback_qusetion_map_id')
		for index, feedback_qusetion_map_id in enumerate(feedback_qusetion_map_ids):
			obj = FeedbackQusetionMap.objects.get(id=feedback_qusetion_map_id)
			if obj.question.is_subjective():
				answer = request.POST.get("answer-%s" %(feedback_qusetion_map_id))
				obj.submitted_answer = answer
				obj.submitted_at=datetime.now()
				obj.save()
			elif obj.question.is_objective():
				answer = request.POST.get("answer-%s" %(feedback_qusetion_map_id))
				option= Option.objects.get(id=answer)
				FeedbackQusetionOptionMap(feedback_qusetion_map=obj,
										  submitted_option=option).save()
				obj.submitted_at=datetime.now()
				obj.save()
			elif obj.question.is_appointment():
				appointment_id = request.POST.get('Time','')
				print "appointment_id  >>>>>>", appointment_id
				appointment_obj = NewAppointment.objects.get(id=appointment_id)
				appointment_obj.make_appointment()
				FeedbackAppointmentMap(feedback=feedback_obj, appointment=appointment_obj,
					submitted_at=datetime.now()).save()
			else:
				answer = request.POST.getlist("answer-%s" %(feedback_qusetion_map_id))
				for single_answer in answer:
					option= Option.objects.get(id=single_answer)
					FeedbackQusetionOptionMap(feedback_qusetion_map=obj,
												  submitted_option=option).save()
					obj.submitted_at=datetime.now()
					obj.save()
					
		obj = Feedback.objects.get(code=code)
		obj.end_feedback()
		return HttpResponseRedirect(reverse('view_thanks'))

class FeedbackSubmittedView(View):
	"""
	"""

	def get(self, request):
		"""
		"""
		return render(request, 'thanks.html', {'msg': 'Thanks for spending your valuable time with us. We have recorded your feedback.'})

class ViewFeedback(View):
	"""
	"""

	def get(self, request, feedback_id):
		feedback = Feedback.objects.get(id=feedback_id)
		if feedback.feedback_type.is_results():
			user_grade_map_obj = UserGradeMap.objects.filter(user=feedback.user)
			return render(request, 'view_feedback.html', {'feedback': feedback, 'user_grade_map_obj':user_grade_map_obj})
		elif feedback.feedback_type.is_appointment():
			feedback_appointment_obj = FeedbackAppointmentMap.objects.get(feedback=feedback)
			return render(request, 'view_feedback.html', {'feedback': feedback, 'feedback_appointment_obj':feedback_appointment_obj})
		else:
			return render(request, 'view_feedback.html', {'feedback': feedback})

class Home(View):
	def get(self, request):
		return render(request, 'calender.html')
	def post(self, request):
		date = request.POST.get('date','')
		dt = datetime.strptime(date, "%Y-%m-%d")
		weekday = dt.weekday()
		available_appointments = Appointment.objects.filter(day=weekday)
		return render(request, 'calender.html',{'data':date, 'available_appointments':available_appointments})

def avail_time_old(request):
	response_data = {}
	date = request.POST.get('date','')
	weekday = date
	available_appointments = Appointment.objects.filter(day=weekday, available='A')
	list1= []
	for obj in available_appointments:
		list1.append({'id':obj.id,'time':obj.start_time})
	#response_data['success'] = True
	#response_data['data'] = serializers.serialize('json', available_appointments)
	response = {'success':True, 'data': date, 'available_appointments': list1}
	#response = {'success':True, 'available_appointments': available_appointments}
	#return HttpResponse(JsonResponse(response_data), content_type="application/json")
	return JsonResponse(response)

def avail_time(request):
	response_data = {}
	date = request.POST.get('date','')
	date = datetime.strptime(date, '%m/%d/%Y').strftime('%Y-%m-%d')
	print "date >>>>>>>>>>>>..", date
	available_appointments = NewAppointment.objects.filter(date=date, available='A')
	print "available_appointments  >>>>>>>>>>", available_appointments
	list1= []
	for obj in available_appointments:
		list1.append({'id':obj.id,'time':str(obj.time_slot)})
	#response_data['success'] = True
	#response_data['data'] = serializers.serialize('json', available_appointments)
	response = {'success':True, 'data': date, 'available_appointments': list1}
	#response = {'success':True, 'available_appointments': available_appointments}
	#return HttpResponse(JsonResponse(response_data), content_type="application/json")
	return JsonResponse(response)

# def email_test(request):
# 	feedbacks = Feedback.objects.filter(user=request.user, status='A').order_by('feedback_type__order_id')
# 	return render(request, 'email_temp.html', {'feedbacks': feedbacks, 'name':request.user.username})

feedback_manager/templates/calender.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  
  <script>
$('#datepicker').datepicker({dateFormat: 'dd/mm/yy'});
  </script>
</head>
<body>
<form action="" method="post">
{% csrf_token %}
<input id="djoined" name="djoined" type="hidden" class="text" type="date">

<input id="datepicker" class="text" size="11" type="date" name="date" value="{% if data %}{{data}}{% else %}{% endif %}">
<input class="btn btn-submit" type="submit" value="Available Time" >

{% if data %}

	<div class="radio-btns">
	<div class="swit">
      {% for appointment in available_appointments %}
            <div class="my_radio">
            <input type="radio"  name="Time" value="{{appointment.start_time}}" /><i></i>{{appointment.start_time}} </div>
      {% endfor %}
	 	</div>
	</div>
<input class="btn btn-submit" type="submit" value="Submit" >
{% endif %}
</form>
</body>
</html>

feedback_manager/templates/email_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>New Horizons Tutorial Center</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        /*.heading {
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #FFFFFF;
            font-weight: 600;
            font-size: 20px;
            line-height: 1.3;
        }*/
        /*.left-padding {
            padding-left: 15px;
        }*/

        /*.main-content {
            font-size: : 14px;
            font-family: Arial,Helvetica,sans-serif;
        }
        .button{
            color: #fff;
            background-color: #337ab7;
            border-color: #2e6da4;
        }*/
    </style>

</head>
<body>

    <div class="container">
        <div class="row" style="background-color: #006699;">
            <div class="col-md-offset-3 col-centered" style="padding: 7px;padding-left: 15px;">
                <span class="heading" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #FFFFFF;
            font-weight: 600;
            font-size: 20px;
            line-height: 1.3;">WelCome</span>
            </div>
        </div>
        <div class="row"  style="background-color: #e9f5fb;padding-bottom: 5px;padding-top: 10px;">
            <div class="col-md-offset-3 col-centered main-content" style="padding: 7px;padding-left: 15px;">
                <p><em>&ldquo;Dear Parent of {{name}}:</em></p>
                <p><em>Thank you very much for enrolling your child in New Horizons Tutorial Center. </em></p>
                <p>&nbsp;</p>
                <p><em>We hope your child is learning and understanding the course materials that are designed for his/her level of proficiency.</em></p>
                <p><em>Please do take some time to visit the links provided by the buttons below in order for us to serve your child better.</em></p>
                <p><em>Please do not hesitate to set up an appointment with the director if so needed. </em></p>
                <p><em>The available time slots for the appointments are obtained by accessing the appropriate button given below.</em></p>
                <p>&nbsp;</p>
                <p><em>Thanking you.</em></p>
                <p><em>With Regards,</em></p>
                <p><em>Dr. A. Adhya, Ph.D.</em></p>
                <p><em>Director, New Horizons Tutorial Center</em></p>
                <p><em>Clarksville, MD 20926</em></p>
            </div>
        </div>
        <div class="row"  style="background-color: #e9f5fb;padding-bottom: 5px;padding-top: 10px;">
            <div class="col-md-offset-1 col-centered">
                
                {% for feedback in feedbacks %}
                <div class="col-md-6 col-xs-12 col-sm-6" style="text-align:{% if forloop.counter|divisibleby:2 %} left;{% else %} right;{% endif %}padding: 3px;width: 40%;display: inline-block;">
                    <a href="https://afternoon-mountain-42194.herokuapp.com/{{feedback.code}}">
                        <button type="button" class="btn btn-primary" style="color: #fff;background-color: #337ab7;border-color: #2e6da4;margin-bottom: 5px;width: 150px;display: inline-block;padding: 6px 12px;font-size: 14px;font-weight: 400;line-height: 1.42857143;text-align: center;white-space: nowrap;vertical-align: middle;cursor: pointer;    border-radius: 4px;border: 1px solid transparent;">{{feedback.feedback_type.get_name_display}}</button>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>

feedback_manager/templates/feedback_form.html
{% load staticfiles %}
<html>
<head>
<title>Feedback Widget Flat Responsive Widget Template :: w3layouts</title>
<!-- for-mobile-apps -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Feedback Widget Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<!-- //for-mobile-apps -->
<link href='//fonts.googleapis.com/css?family=Amaranth:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Josefin+Slab:400,100,100italic,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href="/static/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<style>
th {
    border: solid 2px black;
    padding: 10;
}
td {
	padding: 10;
    border: solid 2px black;
}
</style>

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  
  <script>
  $(document).ready(function() {
    $("#datepicker").datepicker();
  });
  </script>
<body>

	{% if objs.feedback_type.is_results %}
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
    {% if grade_objs %}
    <table class="table table-bordered" style="border: 3px solid black; border-collapse: collapse; margin: auto;">
<!--       <table align="center"> -->

        <thead>

            <tr>
            	<th>Subject</th>

                <th>Grade</th>

            </tr>

        </thead>

        <tbody>
        	 {% for grade_obj in grade_objs %}
            <tr>
            	<td>{{grade_obj.subject}}</td>
                <td>{{grade_obj.grade}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="alert alert-info" style="margin: 25px;">You have not registered for any courses prior to this.<br>Thanks</p>
    {% endif %}
    </div>
    </div>

	{% else %}
	<div class="content">

	<h1>{{objs.feedback_type}}</h1>
	<div class="main">
		<form action="" method="post">
			{% csrf_token %}
			 {% for feedback_qusetion_map in objs.map_feedbacks.all %}
         <input class="quest" type="hidden" name="feedback_qusetion_map_id" value="{{feedback_qusetion_map.id}}">
			<h5>{{feedback_qusetion_map.question.text}}</h5>
					{% if feedback_qusetion_map.question.is_subjective %}
						  <input type="text" name="answer-{{feedback_qusetion_map.id}}" { % if feedback_qusetion_map.submitted_answer % } value="{% if feedback_qusetion_map.submitted_answer %}{{feedback_qusetion_map.submitted_answer}}{% else %}{% endif %}" required="">

					{% elif feedback_qusetion_map.question.is_objective %}
						<div class="radio-btns">
						<div class="swit">
		                  {% for option in feedback_qusetion_map.question.options.all %}
		                        <div class="my_radio">
		                        <input type="radio" required name="answer-{{feedback_qusetion_map.id}}" value="{{option.id}}" /><i></i>{{option}} </div>
		                  {% endfor %}
           			 	</div>
						</div>

          {% elif feedback_qusetion_map.question.is_appointment %}

          <input id="datepicker" class="text" size="11" type="text" name="date" value="{% if data %}{{data}}{% else %}{% endif %} select date">
          <input class="btn btn-submit" id="avail_time" value="Available Time" type="button">
          <br><br>
          <div class="swit" id="avail_radio">
          </div>


					{% else%}
						<div class="radio-btns">
						<div class="swit">
		                  {% for option in feedback_qusetion_map.question.options.all %}
		                        <div class="my_radio">
		                        <input type="checkbox"  name="answer-{{feedback_qusetion_map.id}}" value="{{option.id}}" /><i></i>{{option}} </div>
		                  {% endfor %}
           			 	</div>
						</div>
		      {% endif %}
		    {% endfor %}
                  <input class="btn btn-submit" type="submit" value="Submit" > &nbsp; <p id="successtext"></p>
    <!-- <input id="datepicker" /> -->
    </form>

	</div>
	</div>

	{% endif %}
<script>
// $("#avail_time").click(function(e) {
//     $('#avail_radio').remove()});

$("#avail_time").click(function(e) {
    e.preventDefault();
    // alert($('#datepicker').datepicker({ dateFormat: 'dd-mm-yyyy' }).val());
    $.ajax({
        type: "POST",
        url: "/avail_time/",
        data: {
            date: $('#datepicker').datepicker({ dateFormat: 'yyyy-mm-dd' }).val(),
            'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        
        success: function(response) {
      $('#avail_radio').empty();
      console.log((response.available_appointments).length);
      if ((response.available_appointments).length != 0){
			$.each(response.available_appointments, function(index,element) {
			            console.log(element);
			            $('#avail_radio').append('<div class="my_radio"><div class="my_radio"><input type="radio"  name="Time" value='+element.id+'><i></i>'+element.time+'</div></div>');
			        });
        }
        else{ 
          alert('No appointment available on this date');}
      },
        error: function(result) {
            alert('error');
        }
    });
});

function removeDummy() {
    alert("hello");
}
</script>

</body>
</html>

feedback_manager/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style type="text/css">
.heading {
    font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    color: #FFFFFF;
    font-weight: 600;
    font-size: 20px;
    line-height: 1.3;
}


.left-padding {
    padding-left: 15px;
}

.main-content {
    FONT-SIZE: 14px;
    font-family: Arial,Helvetica,sans-serif;
}
.button{
    color: #fff;
    background-color: #337ab7;
    border-color: #2e6da4;
}
 </style>

</head>
<body>

  <div class="container" style="background-color: #006699;">
    <div class="row">
        <div class="col-md-offset-3 col-centered left-padding">
        <h1 class="heading">Wel-Come</h1>
</div>
</div>
</div>

<div class="container" style="background-color: #e9f5fb;">
    <div class="row">
    <div class="col-md-offset-3 col-centered main-content left-padding">
<p><em>&ldquo;Dear Parent of (*):</em></p>

<p><em>Thank you very much for enrolling your child in New Horizons Tutorial Center. </em></p>

<p>&nbsp;</p>

<p><em>We hope your child is learning and understanding the course materials that are designed for his/her level of proficiency.</em></p>

<p><em>Please do take some time to visit the links provided by the buttons below in order for us to serve your child better.</em></p>

<p><em>Please do not hesitate to set up an appointment with the director if so needed. </em></p>

<p><em>The available time slots for the appointments are obtained by accessing the appropriate button given below.</em></p>

<p>&nbsp;</p>

<p><em>Thanking you.</em></p>

<p><em>With Regards,</em></p>

<p><em>Dr. A. Adhya, Ph.D.</em></p>

<p><em>Director, New Horizons Tutorial Center</em></p>

<p><em>Clarksville, MD 20926</em></p>
  </div>
  </div>
  <div class="row">
    <div class="col-md-offset-3 col-centered">
  </div>
  </div>
  </div>
</body>
</html>

feedback_manager/templates/thanks.html
 {% extends "admin/base_site.html" %}
 {% load i18n %}
 
 {% block title %}
 	Feed back management
 {% endblock %}

 {% block extrahead %}
   <style>
     .row {
       padding: 100px;
     }
   </style>
 {% endblock extrahead %}
 
 {% block sidebar_menu %}{% endblock %}
 {% block breadcrumbs %}{% endblock %}
 {% block main_header %}{% endblock %}
 
 {% block content_container %}
 
   <p class="alert alert-info">{{msg}}</p>
 
{% endblock content_container %}